### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [gmrukwa/divik#81]
Problem
---------
On aarch64, `pip install divik` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install divik` should download the wheels from PyPI.

@gmrukwa, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by gmrukwa** [comment]
Hello @odidev! Yes, I am definitely interested in releasing aarch64 wheels. I will take a look at your PR.

Do you have some time constraints for that? It's quite a hectic time now.

**Comment by odidev** [comment]
No. Please take your time!

**Comment by gmrukwa** [comment]
[Wheels got published](https://pypi.org/project/divik/3.1.0/#files) starting from 3.1.0. Hope everything will work on your end. Feel free to open an issue otherwise. 🙂
